### ISSUE TITLE
fails to build with optparse-applicative 0.18

### ISSUE THREAD

**Issue by juhp** [brendanhay/ede#50]
```
       Preprocessing executable 'ede' for ede-0.3.3.0..                                                                 [304/183885]
       Building executable 'ede' for ede-0.3.3.0..
       [1 of 2] Compiling Main                                                                                                      
        
       /var/stackage/work/unpack-dir/unpacked/ede-0.3.3.0-3642a98f0c978cf9d7ce64edff0f310c79d8c3fbc9d92c8f5f75b0cf41341524/app/Main.
hs:66:11: error: [GHC-76037]
           Not in scope: ‘Pretty.empty’
           NB: the module ‘Options.Applicative.Help.Pretty’ does not export ‘empty’.
           Suggested fix:
             Perhaps use one of these:
               data constructor ‘Pretty.SEmpty’ (imported from Options.Applicative.Help.Pretty),
               ‘Pretty.emptyDoc’ (imported from Options.Applicative.Help.Pretty)
          |
       66 |         [ Pretty.empty,
          |           ^^^^^^^^^^^^
        
       /var/stackage/work/unpack-dir/unpacked/ede-0.3.3.0-3642a98f0c978cf9d7ce64edff0f310c79d8c3fbc9d92c8f5f75b0cf41341524/app/Main.
hs:71:32: error: [GHC-76037]
           Not in scope: ‘Pretty.<$$>’
           NB: the module ‘Options.Applicative.Help.Pretty’ does not export ‘<$$>’.
           Suggested fix:
             Perhaps use one of these:
               ‘Pretty.<>’ (imported from Options.Applicative.Help.Pretty),
               ‘Pretty.<+>’ (imported from Options.Applicative.Help.Pretty),
               ‘Pretty.</>’ (imported from Options.Applicative.Help.Pretty)
          |
       71 |                                Pretty.<$$> "Both objects are merged into one with the keys of \
          |                                ^^^^^^^^^^^
        
       /var/stackage/work/unpack-dir/unpacked/ede-0.3.3.0-3642a98f0c978cf9d7ce64edff0f310c79d8c3fbc9d92c8f5f75b0cf41341524/app/Main.
hs:79:32: error: [GHC-76037]
           Not in scope: ‘Pretty.<$$>’
           NB: the module ‘Options.Applicative.Help.Pretty’ does not export ‘<$$>’.
           Suggested fix:
             Perhaps use one of these:
               ‘Pretty.<>’ (imported from Options.Applicative.Help.Pretty),
               ‘Pretty.<+>’ (imported from Options.Applicative.Help.Pretty),
               ‘Pretty.</>’ (imported from Options.Applicative.Help.Pretty)
          |
       79 |                                Pretty.<$$> "The JSON object is read from STDIN."
          |                                ^^^^^^^^^^^
:
```
