### PR TITLE
Migration from ansi-wl-pprint to prettyprinter

### LINKED ISSUE #38: Failed to compile with trifecta 2.1
Trifecta has switched to `prettyprinter` from `ansi-wl-pprint` which leads to compilation errors. A fast and dirty fix would be adding an upper limit for the trifecta version.

```diff
diff --git a/ede.cabal b/ede.cabal
index 04aa6e3..cc666bc 100644
--- a/ede.cabal
+++ b/ede.cabal
@@ -86,7 +86,7 @@ library
         , text                 >= 1.2
         , text-format          >= 0.3
         , text-manipulate      >= 0.1.2
-        , trifecta             >= 1.6
+        , trifecta             >= 1.6   && < 2.1
         , unordered-containers >= 0.2.3
         , vector               >= 0.7.1
```

### PR DESCRIPTION
**Pull request by lyokha**
Fixes #38 by switching to the latest trifecta-2.1
which also lets compilation of the ede package with ghc-8.8 or newer.

Also:

- Redundant imports were removed (retaining compatibility with older
  base packages).
- MonadFail feature implemented for base >= 4.13

### CODE REVIEW

**Comment by lyokha** [comment]
Btw for ghc-8.8 and newer there still is an issue: package *text-format* has upper version boundary `< 4.13`, but it's easily fixable by adding option `--allow-newer` to `cabal install`

**Comment by alpmestan** [comment]
> Btw for ghc-8.8 and newer there still is an issue: package text-format has upper version boundary < 4.13

This seems fixed thanks to @phadej's revision of `text-format`: https://hackage.haskell.org/package/text-format-0.3.2/revisions/ :tada:

I also emailed @brendanhay to know if there's any way to help out with getting `ede` up to date with its dependencies' changes.
