### ISSUE TITLE
Failed to compile with trifecta 2.1

### ISSUE THREAD

**Issue by lyokha** [brendanhay/ede#38]
Trifecta has switched to `prettyprinter` from `ansi-wl-pprint` which leads to compilation errors. A fast and dirty fix would be adding an upper limit for the trifecta version.

```diff
diff --git a/ede.cabal b/ede.cabal
index 04aa6e3..cc666bc 100644
--- a/ede.cabal
+++ b/ede.cabal
@@ -86,7 +86,7 @@ library
         , text                 >= 1.2
         , text-format          >= 0.3
         , text-manipulate      >= 0.1.2
-        , trifecta             >= 1.6
+        , trifecta             >= 1.6   && < 2.1
         , unordered-containers >= 0.2.3
         , vector               >= 0.7.1
```
